/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package otoeksper;
import javax.swing.JOptionPane;
        import otoeksper.conn;

/**
 *
 * @author ozkan
 */
public class Rapor extends javax.swing.JFrame {

    /**
     * Creates new form Rapor
     */
    public Rapor() {
        initComponents();
    }
    public Rapor(String plaka,String marka,String km){
        initComponents();
        
        lblplaka.setText(plaka);
        lblmarka.setText("MARKA= "+marka);
        lblkm.setText("KM= "+km);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblplaka = new javax.swing.JLabel();
        lblmarka = new javax.swing.JLabel();
        lblkm = new javax.swing.JLabel();
        lblhasar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cmbkaput = new javax.swing.JComboBox<>();
        lblhasar1 = new javax.swing.JLabel();
        cmbBagaj = new javax.swing.JComboBox<>();
        cmbsac = new javax.swing.JComboBox<>();
        cmbsoc = new javax.swing.JComboBox<>();
        cmbsaarkc = new javax.swing.JComboBox<>();
        cmbsolarkc = new javax.swing.JComboBox<>();
        cmbsagonkapi = new javax.swing.JComboBox<>();
        cmbsolok = new javax.swing.JComboBox<>();
        cmbsagark = new javax.swing.JComboBox<>();
        cmbsolark = new javax.swing.JComboBox<>();
        lblhasar2 = new javax.swing.JLabel();
        lblhasar3 = new javax.swing.JLabel();
        lblhasar4 = new javax.swing.JLabel();
        lblhasar5 = new javax.swing.JLabel();
        lblhasar6 = new javax.swing.JLabel();
        lblhasar7 = new javax.swing.JLabel();
        lblhasar8 = new javax.swing.JLabel();
        lblhasar9 = new javax.swing.JLabel();
        lblhasar10 = new javax.swing.JLabel();
        lblplaka2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel1.setText("Rapor");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ozkan\\Desktop\\2-el-arac-satin-alirken-mutlaka-ekspertiz-yapilmali.png")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel3.setText("Kaput");

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel4.setText("Bagaj");

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel5.setText("Sag Çamurluk");

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel6.setText("Sol Arka KApı");

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel7.setText("Sag Arka Kapı");

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel8.setText("Sol Ön Kapı");

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel9.setText("Sol Çamurluk");

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel10.setText("Sag Arka Çamurluk");

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel11.setText("Sol Arka Çamurluk");

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel12.setText("Sag Ön Kapı");

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel13.setText("Araç Bilgisi =");

        lblplaka.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N

        lblmarka.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblmarka.setText("MARKA :");

        lblkm.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblkm.setText("KM :");

        lblhasar.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblhasar.setText("HASAR BILGISI : ");

        jButton1.setText("KAYDET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmbkaput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islemi Seciniz", "Orjinal", "Boyali", "Degisen" }));
        cmbkaput.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbkaputİtemStateChanged(evt);
            }
        });
        cmbkaput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkaputActionPerformed(evt);
            }
        });

        lblhasar1.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N

        cmbBagaj.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islemi Seciniz", "Orjinal", "Boyali", "Degisen" }));
        cmbBagaj.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBagajİtemStateChanged(evt);
            }
        });

        cmbsac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islemi Seciniz", "Orjinal", "Boyali", "Degisen" }));
        cmbsac.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbsacİtemStateChanged(evt);
            }
        });

        cmbsoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islemi Seciniz", "Orjinal", "Boyali", "Degisen" }));
        cmbsoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbsocİtemStateChanged(evt);
            }
        });

        cmbsaarkc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islemi Seciniz", "Orjinal", "Boyali", "Degisen" }));
        cmbsaarkc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbsaarkcİtemStateChanged(evt);
            }
        });

        cmbsolarkc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islemi Seciniz", "Orjinal", "Boyali", "Degisen" }));
        cmbsolarkc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbsolarkcİtemStateChanged(evt);
            }
        });

        cmbsagonkapi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islemi Seciniz", "Orjinal", "Boyali", "Degisen" }));
        cmbsagonkapi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbsagonkapiİtemStateChanged(evt);
            }
        });

        cmbsolok.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islemi Seciniz", "Orjinal", "Boyali", "Degisen" }));
        cmbsolok.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbsolokİtemStateChanged(evt);
            }
        });

        cmbsagark.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islemi Seciniz", "Orjinal", "Boyali", "Degisen" }));
        cmbsagark.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbsagarkİtemStateChanged(evt);
            }
        });

        cmbsolark.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islemi Seciniz", "Orjinal", "Boyali", "Degisen" }));
        cmbsolark.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbsolarkİtemStateChanged(evt);
            }
        });

        lblhasar2.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N

        lblhasar3.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N

        lblhasar4.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N

        lblhasar5.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N

        lblhasar6.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N

        lblhasar7.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N

        lblhasar8.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N

        lblhasar9.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N

        lblhasar10.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N

        lblplaka2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblplaka2.setText("PLAKA :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbkaput, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(160, 160, 160))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbBagaj, 0, 235, Short.MAX_VALUE)
                                    .addComponent(cmbsolark, 0, 235, Short.MAX_VALUE)
                                    .addComponent(cmbsac, 0, 235, Short.MAX_VALUE)
                                    .addComponent(cmbsoc, 0, 235, Short.MAX_VALUE)
                                    .addComponent(cmbsaarkc, 0, 235, Short.MAX_VALUE)
                                    .addComponent(cmbsolarkc, 0, 235, Short.MAX_VALUE)
                                    .addComponent(cmbsagonkapi, 0, 235, Short.MAX_VALUE)
                                    .addComponent(cmbsolok, 0, 235, Short.MAX_VALUE)
                                    .addComponent(cmbsagark, 0, 235, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblhasar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblhasar1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblhasar2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblhasar3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblhasar6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblhasar7, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblhasar8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblhasar9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblhasar10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lblhasar4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblhasar5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmarka, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblkm, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblplaka2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblplaka, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(69, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbkaput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbBagaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbsac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbsoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbsaarkc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbsolarkc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbsagonkapi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(cmbsolok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbsagark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbsolark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(27, 27, 27)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblplaka2)
                    .addComponent(lblplaka, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(lblmarka)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblkm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhasar)
                    .addComponent(lblhasar1)
                    .addComponent(lblhasar2)
                    .addComponent(lblhasar3)
                    .addComponent(lblhasar4)
                    .addComponent(lblhasar5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhasar6)
                    .addComponent(lblhasar7)
                    .addComponent(lblhasar8)
                    .addComponent(lblhasar9)
                    .addComponent(lblhasar10))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbkaputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkaputActionPerformed
    
        
        
        
    }//GEN-LAST:event_cmbkaputActionPerformed

    private void cmbkaputİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbkaputİtemStateChanged
      lblhasar1.setText("Kaput= "+cmbkaput.getSelectedItem().toString());
    }//GEN-LAST:event_cmbkaputİtemStateChanged

    private void cmbBagajİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBagajİtemStateChanged
      lblhasar2.setText("Bagaj= "+cmbBagaj.getSelectedItem().toString());
    }//GEN-LAST:event_cmbBagajİtemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           conn cn=new conn();
      cn.Baglan(); 
      String sorgu="INSERT INTO tblhasar(plaka, kaput, bagaj, sagcamurluk, solcamurluk, sagarkacamurluk, solarkacamurluk, solkapi, sagkapi, sagarkakapi, solarkakapi) VALUES "
              + "('"+lblplaka.getText()+"','"+cmbkaput.getSelectedItem().toString()+"', '"
              + ""+cmbBagaj.getSelectedItem().toString()+"', '"
              + ""+cmbsac.getSelectedItem().toString()+"', '"
              + ""+cmbsoc.getSelectedItem().toString()+"','"
              + ""+cmbsaarkc.getSelectedItem().toString()+"' , '"
              + ""+cmbsolarkc.getSelectedItem().toString()+"', '"
              + ""+cmbsolok.getSelectedItem().toString()+"', '"
              + ""+cmbsagonkapi.getSelectedItem().toString()+"', '"
              + ""+cmbsagark.getSelectedItem().toString()+"', '"
              + ""+cmbsolark.getSelectedItem().toString()+"')";
            

      cn.Ekle(sorgu);
        JOptionPane.showMessageDialog(rootPane, "Yaptım");
      setVisible(false);
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbsacİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbsacİtemStateChanged
         lblhasar3.setText("Sag Çamurluk= "+cmbsac.getSelectedItem().toString());
    }//GEN-LAST:event_cmbsacİtemStateChanged

    private void cmbsocİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbsocİtemStateChanged
      lblhasar4.setText("Sol Çamurluk= "+cmbsoc.getSelectedItem().toString());
    }//GEN-LAST:event_cmbsocİtemStateChanged

    private void cmbsaarkcİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbsaarkcİtemStateChanged
       lblhasar5.setText("Sag Arka Çamurluk= "+cmbsaarkc.getSelectedItem().toString());
    }//GEN-LAST:event_cmbsaarkcİtemStateChanged

    private void cmbsolarkcİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbsolarkcİtemStateChanged
        lblhasar6.setText("Sol Arka Çamurluk= "+cmbsolarkc.getSelectedItem().toString());
    }//GEN-LAST:event_cmbsolarkcİtemStateChanged

    private void cmbsagonkapiİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbsagonkapiİtemStateChanged
         lblhasar7.setText("Sag Ön Kapı= "+cmbsagonkapi.getSelectedItem().toString());
    }//GEN-LAST:event_cmbsagonkapiİtemStateChanged

    private void cmbsolokİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbsolokİtemStateChanged
       lblhasar8.setText("Sol Ön Kapı= "+cmbsolok.getSelectedItem().toString());
    }//GEN-LAST:event_cmbsolokİtemStateChanged

    private void cmbsagarkİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbsagarkİtemStateChanged
        lblhasar9.setText("Sag Arka Kapı= "+cmbsagark.getSelectedItem().toString());
    }//GEN-LAST:event_cmbsagarkİtemStateChanged

    private void cmbsolarkİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbsolarkİtemStateChanged
     lblhasar10.setText("Sol Arka Kapı= "+cmbsolark.getSelectedItem().toString());
    }//GEN-LAST:event_cmbsolarkİtemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rapor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rapor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rapor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rapor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rapor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JComboBox<String> cmbBagaj;
    private javax.swing.JComboBox<String> cmbkaput;
    private javax.swing.JComboBox<String> cmbsaarkc;
    private javax.swing.JComboBox<String> cmbsac;
    private javax.swing.JComboBox<String> cmbsagark;
    private javax.swing.JComboBox<String> cmbsagonkapi;
    private javax.swing.JComboBox<String> cmbsoc;
    private javax.swing.JComboBox<String> cmbsolark;
    private javax.swing.JComboBox<String> cmbsolarkc;
    private javax.swing.JComboBox<String> cmbsolok;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblhasar;
    private javax.swing.JLabel lblhasar1;
    private javax.swing.JLabel lblhasar10;
    private javax.swing.JLabel lblhasar2;
    private javax.swing.JLabel lblhasar3;
    private javax.swing.JLabel lblhasar4;
    private javax.swing.JLabel lblhasar5;
    private javax.swing.JLabel lblhasar6;
    private javax.swing.JLabel lblhasar7;
    private javax.swing.JLabel lblhasar8;
    private javax.swing.JLabel lblhasar9;
    private javax.swing.JLabel lblkm;
    private javax.swing.JLabel lblmarka;
    private javax.swing.JLabel lblplaka;
    private javax.swing.JLabel lblplaka2;
    // End of variables declaration//GEN-END:variables
}
